"""Regenerate the website's entire achievements list from the dashboard.

    data/achievements.ts   fully rewritten, every time

Replaces the old export_achievements.py (deleted 2026-09-22), which could
only ever APPEND new member-reported results onto the 189 hand-compiled
historical entries already in the file — never edit or remove anything on
either side. public_achievements (see its comment in supabase_schema.sql)
is now the one flat, fully host-editable table this file is generated
from, so this script does a straight full rewrite, the same shape as
export_members.py already uses for data/members.ts.

    python export_public_achievements.py --dry-run     see what would change
    python export_public_achievements.py                write it

Deliberately not automatic, same reasoning as export_members.py: run it,
look at the diff, commit it yourself.
"""

import argparse
import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from supabase import create_client

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).resolve().parent
SITE = Path(os.environ.get("ROBOKNIGHTS_SITE_REPO",
                           Path.home() / "Documents/GitHub/RoboKnights-Clan.github.io"))
ACHIEVEMENTS_TS = SITE / "data" / "achievements.ts"


def render(rows):
    lines = [
        "// GENERATED by export_public_achievements.py in the roboknights-inventory",
        "// repo, from the public_achievements table. Do not edit by hand - the next",
        "// export overwrites it. To add, edit or remove a result, use the Website:",
        "// Results page in the dashboard.",
        "",
        "export const achievements = [",
    ]
    for row in rows:
        members_json = ", ".join(json.dumps(m, ensure_ascii=False) for m in (row.get("members") or []))
        lines.append("  {")
        lines.append(f'    competition: {json.dumps(row["competition"], ensure_ascii=False)},')
        lines.append(f'    level: {json.dumps(row["level"], ensure_ascii=False)},')
        lines.append(f'    year: {json.dumps(row["year"], ensure_ascii=False)},')
        lines.append(f'    prize: {json.dumps(row["prize"], ensure_ascii=False)},')
        lines.append(f'    members: [{members_json}]')
        lines.append("  },")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="print what would change, write nothing")
    args = parser.parse_args()

    load_dotenv(HERE / ".env")
    client = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_KEY"])

    try:
        rows = client.table("public_achievements").select("*").execute().data
    except Exception as error:
        # PostgREST's real wording for a missing table is "Could not
        # find the table ... in the schema cache" (code PGRST205), not
        # "does not exist" - checking only the latter meant this never
        # actually caught anything.
        if "does not exist" not in str(error) and "PGRST205" not in str(error):
            raise
        print("NOTE: public_achievements doesn't exist yet - run the migration at")
        print("      the end of supabase_schema.sql in Supabase's SQL editor, then")
        print("      python import_public_achievements.py once, before this script")
        print("      has anything to export.")
        return

    if not rows:
        print("public_achievements is empty - nothing to export. If this is the")
        print("first run, see import_public_achievements.py.")
        return

    # Newest first, matching the order the file has always been in.
    rows.sort(key=lambda r: r.get("year") or "", reverse=True)

    new_text = render(rows)
    print(f"{len(rows)} result(s) in public_achievements")

    if args.dry_run:
        old_text = ACHIEVEMENTS_TS.read_text(encoding="utf-8") if ACHIEVEMENTS_TS.exists() else ""
        if old_text == new_text:
            print("--dry-run: no change from what's already on disk")
        else:
            print(f"--dry-run: {ACHIEVEMENTS_TS} would change")
        return

    if not SITE.exists():
        sys.exit(f"Website repo not found at {SITE}. Set ROBOKNIGHTS_SITE_REPO.")

    ACHIEVEMENTS_TS.write_text(new_text, encoding="utf-8", newline="\n")
    print(f"wrote {ACHIEVEMENTS_TS}")
    print("Now look at the diff in the website repo and commit it if it's right.")


if __name__ == "__main__":
    main()
