"""Build the website's member list from the dashboard.

Writes two things into the website repo:

    data/members.ts              the roster
    public/images/roster/*.jpg   only the photos people ticked to publish

Run it whenever the roster changes, look at the diff, and commit it. It is
deliberately not automatic: this puts real students' names and faces on a
public website, and that should be something a person chose to do, not
something a cron job did at 3am.

    python export_members.py --dry-run     see what would change
    python export_members.py               write it

Decisions baked in here, all made by the student on 2026-08-31:

  * The dashboard is the roster. Anyone without an account is not listed.
  * Photos are published only where photo_public is true. Having uploaded
    one is not enough.
  * Names are title-cased for the website. The dashboard keeps whatever
    members typed; ALL CAPS is fine in a form and shouting on a page.
  * "Aviral Chadda" and "Aviral Chadha" were one person spelled two ways.
  * Social handles become links here. The website stores no urls, which is
    how it ended up with 105 links to instagram.com's front page.
"""

import argparse
import json
import os
import re
import sys
from pathlib import Path

from dotenv import load_dotenv
from supabase import create_client

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).resolve().parent
SITE = Path(os.environ.get("ROBOKNIGHTS_SITE_REPO",
                           Path.home() / "Documents/GitHub/RoboKnights-Clan.github.io"))
MEMBERS_TS = SITE / "data" / "members.ts"
# NOT public/images/members - that directory already exists and holds the
# 40 ALUMNI photos referenced by data/alumni.ts. An earlier version of this
# script wiped it, which would have broken every photo on the Alumni page.
# Current members get their own directory, and nothing else writes here.
PHOTO_DIR = SITE / "public" / "images" / "roster"
BUCKET = "member-photos"

# Not people: the club's own login.
EXCLUDE_NAMES = {"roboknights clan"}

ROLE_LABEL = {"core_member": "Core Member", "member": "Member", "adhoc": "Member"}

# Grade -> the heading it appears under. Anything else is skipped rather
# than guessed at, and reported so it is not silently lost.
GRADE_HEADING = {12: "Class 12", 11: "Class 11", 10: "Class 10", 9: "Class 9",
                 8: "Class 8", 7: "Class 7"}
HEADING_ORDER = ["Class 12", "Class 11", "Class 10", "Class 9", "Class 8", "Class 7"]

LOWERCASE_PARTICLES = {"de", "van", "der", "da", "di", "bin", "binte"}


def tidy_name(raw):
    """Title-case for display, without mangling the parts that are correct."""
    # "ANJUSHREE SAHU 07E 2026-2027" -> the section code and session are not
    # part of anyone's name.
    name = re.sub(r"\b\d{1,2}[A-Za-z]?\b", " ", raw or "")
    name = re.sub(r"\b20\d\d\s*-\s*20\d\d\b", " ", name)
    name = re.sub(r"\s+", " ", name).strip()

    def fix(word):
        if word.lower() in LOWERCASE_PARTICLES:
            return word.lower()
        # Leave anything already mixed-case alone: "McCarthy", "DeSouza".
        if word[1:] != word[1:].lower() and word != word.upper():
            return word
        return word[:1].upper() + word[1:].lower()

    return " ".join(fix(w) for w in name.split(" ") if w)


def socials_for(row):
    out = []
    if row.get("instagram"):
        out.append(("instagram", f"https://www.instagram.com/{row['instagram']}"))
    if row.get("linkedin"):
        out.append(("linkedin", f"https://www.linkedin.com/in/{row['linkedin']}"))
    if row.get("github"):
        out.append(("github", f"https://github.com/{row['github']}"))
    return out


def render(groups):
    lines = [
        "// GENERATED by export_members.py in the roboknights-inventory repo.",
        "// Do not edit by hand - the next export overwrites it. To change",
        "// someone's name, photo or links, change them in the dashboard.",
        "",
        "export const members = [",
    ]
    for heading, people in groups:
        lines.append("  {")
        lines.append(f'    year: {json.dumps(heading)},')
        lines.append("    members: [")
        for person in people:
            lines.append("      {")
            lines.append(f'        name: {json.dumps(person["name"])},')
            lines.append(f'        role: {json.dumps(person["role"])},')
            lines.append(f'        src: {json.dumps(person["src"])},')
            if person["socials"]:
                lines.append("        socials: [")
                for kind, url in person["socials"]:
                    lines.append(
                        f'          {{ type: {json.dumps(kind)}, url: {json.dumps(url)} }},'
                    )
                lines.append("        ],")
            else:
                lines.append("        socials: [],")
            lines.append("      },")
        lines.append("    ],")
        lines.append("  },")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="print what would change, write nothing")
    args = parser.parse_args()

    load_dotenv(HERE / ".env")
    client = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_KEY"])

    profile_columns = "photo_path,photo_public,instagram,linkedin,github"
    base = "user_id,name,grade,role,is_staff,is_disabled"
    try:
        rows = client.table("users").select(f"{base},{profile_columns}").execute().data
    except Exception as error:
        # The profile columns are added by the migration at the bottom of
        # supabase_schema.sql. Until someone runs it there are no photos or
        # links to export - but the roster itself is still worth building,
        # so this carries on rather than refusing.
        if "does not exist" not in str(error):
            raise
        print("NOTE: the profile columns are missing, so no photos or links")
        print("      will be exported. Run the migration at the end of")
        print("      supabase_schema.sql in Supabase's SQL editor, then")
        print("      re-run this. The roster below is still correct.\n")
        rows = client.table("users").select(base).execute().data

    people, skipped = [], []
    seen = set()
    for row in rows:
        raw = (row.get("name") or "").strip()
        if not raw or raw.lower() in EXCLUDE_NAMES:
            continue
        if row.get("is_staff"):
            continue
        if row.get("is_disabled"):
            skipped.append((raw, "account disabled"))
            continue

        heading = GRADE_HEADING.get(row.get("grade"))
        if heading is None:
            skipped.append((raw, f"grade {row.get('grade')!r} - no heading for it"))
            continue

        name = tidy_name(raw)
        # One row per person. The users table has a duplicate ("Eeshitv"
        # twice), and two spellings of Aviral. Either would appear twice on
        # a public page, which looks like carelessness because it is.
        fingerprint = re.sub(r"[^a-z]", "", name.lower())[:12]
        if fingerprint in seen:
            skipped.append((raw, "duplicate of someone already listed"))
            continue
        seen.add(fingerprint)

        people.append({
            "heading": heading,
            "name": name,
            "role": ROLE_LABEL.get(row.get("role"), "Member"),
            "photo_path": row.get("photo_path") if row.get("photo_public") else None,
            "socials": socials_for(row),
            "src": "",
        })

    groups = []
    for heading in HEADING_ORDER:
        members = sorted(
            (p for p in people if p["heading"] == heading),
            # Core members first, then alphabetical.
            key=lambda p: (p["role"] != "Core Member", p["name"].lower()),
        )
        if members:
            groups.append((heading, members))

    publishing = [p for p in people if p["photo_path"]]

    print(f"{len(people)} members across {len(groups)} classes")
    print(f"{len(publishing)} publishing a photo")
    for heading, members in groups:
        core = sum(1 for m in members if m["role"] == "Core Member")
        print(f"   {heading:<10} {len(members):>3}" + (f"  ({core} core)" if core else ""))
    if skipped:
        print("\nnot listed:")
        for name, why in skipped:
            print(f"   {name:<32} {why}")

    if args.dry_run:
        print("\n--dry-run: nothing written")
        return

    if not SITE.exists():
        sys.exit(f"Website repo not found at {SITE}. Set ROBOKNIGHTS_SITE_REPO.")

    # Un-ticking "show my photo on the website" has to actually remove the
    # file, or it stays served forever. So stale files are deleted - but
    # only ones this script could have written, matched by name against the
    # user ids we know about. Never a blanket wipe of the directory: the
    # first version of this did that to a directory it did not own.
    PHOTO_DIR.mkdir(parents=True, exist_ok=True)
    wanted = {person["photo_path"] for person in publishing}
    known_ids = {str(row.get("user_id")) for row in rows}
    for existing in PHOTO_DIR.iterdir():
        if not existing.is_file():
            continue
        if existing.name in wanted:
            continue
        if existing.stem in known_ids:
            existing.unlink()          # a member who has un-published
        else:
            print(f"   left alone (not ours): {existing.name}")

    for person in publishing:
        path = person["photo_path"]
        try:
            data = client.storage.from_(BUCKET).download(path)
        except Exception as error:
            print(f"   could not fetch {path}: {error}")
            continue
        (PHOTO_DIR / path).write_bytes(data)
        person["src"] = f"/images/roster/{path}"

    MEMBERS_TS.write_text(render(groups), encoding="utf-8", newline="\n")
    print(f"\nwrote {MEMBERS_TS}")
    print(f"wrote {len(publishing)} photo(s) to {PHOTO_DIR}")
    print("\nNow look at the diff in the website repo and commit it if it is right.")


if __name__ == "__main__":
    main()
