"""Regenerate the website's Alumni page from the dashboard.

    data/alumni.ts   fully rewritten, every time

public_alumni (see its comment in supabase_schema.sql) is one flat row
per person; this regroups them back into the nested
{ batch, people: [...] } shape pages/alumni.tsx expects, same full-rewrite
shape export_members.py and export_public_achievements.py already use.

    python export_public_alumni.py --dry-run     see what would change
    python export_public_alumni.py                write it

Deliberately not automatic: run it, look at the diff, commit it yourself.
"""

import argparse
import json
import os
import sys
from collections import OrderedDict
from pathlib import Path

from dotenv import load_dotenv
from supabase import create_client

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

HERE = Path(__file__).resolve().parent
SITE = Path(os.environ.get("ROBOKNIGHTS_SITE_REPO",
                           Path.home() / "Documents/GitHub/RoboKnights-Clan.github.io"))
ALUMNI_TS = SITE / "data" / "alumni.ts"


def group_by_batch(rows):
    # Preserves each row's insertion order (public_alumni_id ascending,
    # since that's how Supabase returns them by default) within a batch -
    # matches the original file's ordering for migrated rows, and puts a
    # newly-added person at the end of their batch's list, which is where
    # a host would expect one to land.
    groups = OrderedDict()
    for row in rows:
        groups.setdefault(row["batch"], []).append(row)
    # Newest batch first - "2025-26" > "2024-25" > ... > "2002-03" sorts
    # correctly as a plain string compare for this "YYYY-YY" format.
    return sorted(groups.items(), key=lambda kv: kv[0], reverse=True)


def render(rows):
    lines = [
        "// GENERATED by export_public_alumni.py in the roboknights-inventory repo,",
        "// from the public_alumni table. Do not edit by hand - the next export",
        "// overwrites it. To add, edit or remove an alumnus, use the Website page",
        "// in the dashboard.",
        "",
        "export const alumni = [",
    ]
    for batch, people in group_by_batch(rows):
        lines.append("  {")
        lines.append(f'    batch: {json.dumps(batch, ensure_ascii=False)},')
        lines.append("    people: [")
        for person in people:
            lines.append("      {")
            lines.append(f'        name: {json.dumps(person["name"], ensure_ascii=False)},')
            lines.append(f'        role: {json.dumps(person.get("role") or "", ensure_ascii=False)},')
            lines.append(f'        src: {json.dumps(person.get("src") or "", ensure_ascii=False)},')
            socials = person.get("socials") or []
            if socials:
                lines.append("        socials: [")
                for social in socials:
                    lines.append(
                        f'          {{ type: {json.dumps(social["type"], ensure_ascii=False)}, '
                        f'url: {json.dumps(social["url"], ensure_ascii=False)} }},'
                    )
                lines.append("        ],")
            else:
                lines.append("        socials: [],")
            lines.append("      },")
        lines.append("    ],")
        lines.append("  },")
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true",
                        help="print what would change, write nothing")
    args = parser.parse_args()

    load_dotenv(HERE / ".env")
    client = create_client(os.environ["SUPABASE_URL"], os.environ["SUPABASE_KEY"])

    try:
        rows = client.table("public_alumni").select("*").execute().data
    except Exception as error:
        # PostgREST's real wording for a missing table is "Could not
        # find the table ... in the schema cache" (code PGRST205), not
        # "does not exist" - checking only the latter meant this never
        # actually caught anything.
        if "does not exist" not in str(error) and "PGRST205" not in str(error):
            raise
        print("NOTE: public_alumni doesn't exist yet - run the migration at the end")
        print("      of supabase_schema.sql in Supabase's SQL editor, then")
        print("      python import_public_alumni.py once, before this script has")
        print("      anything to export.")
        return

    if not rows:
        print("public_alumni is empty - nothing to export. If this is the first")
        print("run, see import_public_alumni.py.")
        return

    new_text = render(rows)
    print(f"{len(rows)} alumnus/alumni row(s) in public_alumni")

    if args.dry_run:
        old_text = ALUMNI_TS.read_text(encoding="utf-8") if ALUMNI_TS.exists() else ""
        if old_text == new_text:
            print("--dry-run: no change from what's already on disk")
        else:
            print(f"--dry-run: {ALUMNI_TS} would change")
        return

    if not SITE.exists():
        sys.exit(f"Website repo not found at {SITE}. Set ROBOKNIGHTS_SITE_REPO.")

    ALUMNI_TS.write_text(new_text, encoding="utf-8", newline="\n")
    print(f"wrote {ALUMNI_TS}")
    print("Now look at the diff in the website repo and commit it if it's right.")


if __name__ == "__main__":
    main()
