-- Run this once in the Supabase SQL Editor to create the three tables.
-- Same shape as the old SQLite tables, with one change: user_id is now a
-- UUID instead of a plain number, because Chunk 7 will make it match the
-- real login account's id from Supabase Auth.

create extension if not exists pgcrypto;

create table if not exists users (
    user_id uuid primary key default gen_random_uuid(),
    name    text not null,
    email   text not null
);

create table if not exists parts (
    part_id     bigint generated by default as identity primary key,
    part_number text not null,
    name        text not null,
    owner_id    uuid not null references users(user_id),
    status      text not null default 'available'
);

create table if not exists requests (
    request_id   bigint generated by default as identity primary key,
    part_id      bigint not null references parts(part_id),
    requester_id uuid not null references users(user_id),
    owner_id     uuid not null references users(user_id),
    status       text not null default 'pending',
    created_at   timestamptz not null default now()
);

-- Added later, for loan due dates. Run this too if you're setting up a
-- fresh project from scratch; if your requests table already exists,
-- just run these two lines on their own.
alter table requests add column if not exists requested_days integer;
alter table requests add column if not exists due_date date;

-- Added later, for the "due soon" reminder emails. Tracks whether each
-- reminder has already gone out, so the daily job never sends the same
-- one twice.
alter table requests add column if not exists reminder_2day_sent boolean not null default false;
alter table requests add column if not exists reminder_1day_sent boolean not null default false;

-- Added later, for the Competitions feature. Students self-report their
-- grade at signup; events later filter who's eligible to volunteer by this.
alter table users add column if not exists grade integer;

-- Competitions feature, Chunk 1 (foundation): a competition has many links
-- and many events; events carry their own eligible grade range.
create table if not exists competitions (
    competition_id        bigint generated by default as identity primary key,
    name                  text not null,
    venue                 text,
    competition_date      date,
    registration_deadline date,
    student_incharge      text,
    created_at            timestamptz not null default now()
);

create table if not exists competition_links (
    link_id        bigint generated by default as identity primary key,
    competition_id bigint not null references competitions(competition_id) on delete cascade,
    label          text not null,
    url            text not null
);

create table if not exists competition_events (
    event_id       bigint generated by default as identity primary key,
    competition_id bigint not null references competitions(competition_id) on delete cascade,
    name           text not null,
    details        text,
    team_size      integer not null default 1,
    max_teams      integer not null default 1,
    min_grade      integer not null default 7,
    max_grade      integer not null default 12
);

-- Competitions feature, Chunk 3: students volunteering for eligible events.
-- Just tracks who's expressed interest — no "selected" column yet, since
-- finalizing volunteers (the "green cell" step) is a later chunk that'll
-- add it then.
create table if not exists event_volunteers (
    volunteer_id bigint generated by default as identity primary key,
    event_id     bigint not null references competition_events(event_id) on delete cascade,
    user_id      uuid not null references users(user_id) on delete cascade,
    created_at   timestamptz not null default now(),
    unique (event_id, user_id)
);
