-- Run this once in the Supabase SQL Editor to create the three tables.
-- Same shape as the old SQLite tables, with one change: user_id is now a
-- UUID instead of a plain number, because Chunk 7 will make it match the
-- real login account's id from Supabase Auth.

create extension if not exists pgcrypto;

create table if not exists users (
    user_id uuid primary key default gen_random_uuid(),
    name    text not null,
    email   text not null
);

create table if not exists parts (
    part_id     bigint generated by default as identity primary key,
    part_number text not null,
    name        text not null,
    owner_id    uuid not null references users(user_id),
    status      text not null default 'available'
);

create table if not exists requests (
    request_id   bigint generated by default as identity primary key,
    part_id      bigint not null references parts(part_id),
    requester_id uuid not null references users(user_id),
    owner_id     uuid not null references users(user_id),
    status       text not null default 'pending',
    created_at   timestamptz not null default now()
);

-- Added later, for loan due dates. Run this too if you're setting up a
-- fresh project from scratch; if your requests table already exists,
-- just run these two lines on their own.
alter table requests add column if not exists requested_days integer;
alter table requests add column if not exists due_date date;

-- Added later, for the "due soon" reminder emails. Tracks whether each
-- reminder has already gone out, so the daily job never sends the same
-- one twice.
alter table requests add column if not exists reminder_2day_sent boolean not null default false;
alter table requests add column if not exists reminder_1day_sent boolean not null default false;

-- Added later, for the Competitions feature. Students self-report their
-- grade at signup; events later filter who's eligible to volunteer by this.
alter table users add column if not exists grade integer;

-- Competitions feature, Chunk 1 (foundation): a competition has many links
-- and many events; events carry their own eligible grade range.
create table if not exists competitions (
    competition_id        bigint generated by default as identity primary key,
    name                  text not null,
    venue                 text,
    competition_date      date,
    registration_deadline date,
    student_incharge      text,
    created_at            timestamptz not null default now()
);

create table if not exists competition_links (
    link_id        bigint generated by default as identity primary key,
    competition_id bigint not null references competitions(competition_id) on delete cascade,
    label          text not null,
    url            text not null
);

create table if not exists competition_events (
    event_id       bigint generated by default as identity primary key,
    competition_id bigint not null references competitions(competition_id) on delete cascade,
    name           text not null,
    details        text,
    team_size      integer not null default 1,
    max_teams      integer not null default 1,
    min_grade      integer not null default 7,
    max_grade      integer not null default 12
);

-- Competitions feature, Chunk 3: students volunteering for eligible events.
-- Just tracks who's expressed interest — no "selected" column yet, since
-- finalizing volunteers (the "green cell" step) is a later chunk that'll
-- add it then.
create table if not exists event_volunteers (
    volunteer_id bigint generated by default as identity primary key,
    event_id     bigint not null references competition_events(event_id) on delete cascade,
    user_id      uuid not null references users(user_id) on delete cascade,
    created_at   timestamptz not null default now(),
    unique (event_id, user_id)
);

-- Added later, for the fuller signup form. "email" is already the login
-- address (relabeled "Institutional email" in the UI, not a separate column).
alter table users add column if not exists section text;
alter table users add column if not exists admission_no text;
alter table users add column if not exists phone_no text;

-- Meeting scheduler: a meeting has an external join link (Google Meet,
-- Jitsi, etc.) rather than real video calling built in. RSVP and
-- attendance are separate tables since attending without RSVPing (or
-- RSVPing but not attending) both need to be possible.
create table if not exists meetings (
    meeting_id   bigint generated by default as identity primary key,
    title        text not null,
    agenda       text,
    meeting_date date not null,
    meeting_time time,
    join_link    text,
    created_at   timestamptz not null default now()
);
-- Optional extras — plenty of meetings (a plain Jitsi link) don't need them.
alter table meetings add column if not exists meeting_id_code text;
alter table meetings add column if not exists meeting_password text;

create table if not exists meeting_rsvps (
    rsvp_id    bigint generated by default as identity primary key,
    meeting_id bigint not null references meetings(meeting_id) on delete cascade,
    user_id    uuid not null references users(user_id) on delete cascade,
    created_at timestamptz not null default now(),
    unique (meeting_id, user_id)
);

-- Existence of a row = present. Self-checked-in by default; host can add
-- or remove anyone afterward via the Attendance multiselect.
create table if not exists meeting_attendance (
    attendance_id bigint generated by default as identity primary key,
    meeting_id    bigint not null references meetings(meeting_id) on delete cascade,
    user_id       uuid not null references users(user_id) on delete cascade,
    created_at    timestamptz not null default now(),
    unique (meeting_id, user_id)
);

-- Achievements: any member logs their own result for a competition event
-- afterward (position + an optional link to photos/video, not a real file
-- upload — this app has no file storage set up). Self-reported, like most
-- of this app; host can delete an entry too (e.g. a mistake or duplicate).
create table if not exists achievements (
    achievement_id bigint generated by default as identity primary key,
    user_id        uuid not null references users(user_id) on delete cascade,
    competition_id bigint not null references competitions(competition_id) on delete cascade,
    event_id       bigint not null references competition_events(event_id) on delete cascade,
    position       text,
    media_link     text,
    created_at     timestamptz not null default now()
);

-- Stops the 4pm-on-competition-day achievement reminder from emailing the
-- same person twice, same pattern as the other reminder_*_sent columns.
alter table event_volunteers add column if not exists achievement_reminder_sent boolean not null default false;

-- Competitions feature, Chunk 4: host finalizing volunteers. Capped at
-- team_size * max_teams in the app, not the database.
alter table event_volunteers add column if not exists selected boolean not null default false;

-- Competitions feature, Chunk 5: day-before reminder + bot status.
-- reminder_sent stops the daily job emailing the same person twice, same
-- pattern as requests.reminder_2day_sent/reminder_1day_sent.
alter table event_volunteers add column if not exists bot_status text;
alter table event_volunteers add column if not exists reminder_sent boolean not null default false;

-- Competitions feature, Chunk 6: announcements are now saved (not just
-- emailed) so students have somewhere to see past ones, not just their inbox.
create table if not exists announcements (
    announcement_id bigint generated by default as identity primary key,
    subject         text not null,
    body            text not null,
    created_at      timestamptz not null default now()
);

-- Private student queries: a student starts a thread, only they and the
-- host can see it. Redesigned same day into a real back-and-forth: queries
-- is now just the thread container, and every message (the original
-- question, replies, answers, from either side) lives in query_messages.
-- The old question/answer/status/answered_at columns are unused now but
-- left in place rather than dropped, matching how this project never
-- removes columns, only adds them.
create table if not exists queries (
    query_id    bigint generated by default as identity primary key,
    student_id  uuid not null references users(user_id) on delete cascade,
    question    text not null,
    answer      text,
    status      text not null default 'pending',
    created_at  timestamptz not null default now(),
    answered_at timestamptz
);
alter table queries alter column question drop not null;

-- Competitions: mark one "past" so it drops out of the main list. The host
-- can set this by hand (e.g. a cancelled event), and the app also flips it
-- automatically once competition_date has gone by (checked on page load —
-- see app_pages/competitions.py — since that's frequent enough not to need
-- a scheduled job like the reminder emails do).
alter table competitions add column if not exists is_past boolean not null default false;

-- Groups volunteers into teams for a given event, so logging an
-- achievement for yourself can auto-log it for the rest of your team too.
-- Nullable: a volunteer nobody's grouped into a team yet just has no team.
alter table event_volunteers add column if not exists team_no integer;

-- Host marks a competition RoboKnights isn't sending anyone to. Separate
-- from is_past (a competition can be skipped well before its date) and
-- from deleting (the competition/events stay visible for reference, just
-- with volunteering turned off).
alter table competitions add column if not exists not_attending boolean not null default false;

-- Asking for several identical parts at once (e.g. 3 of the 4 Johnson
-- motors) still creates one request row per physical unit, because each
-- unit is lent and returned independently. They all share this id so the
-- owner sees a single card and makes ONE approve/reject decision for the
-- batch instead of repeating it per unit. Null on older single-unit
-- requests made before this existed — treat those as a group of one.
alter table requests add column if not exists request_group_id uuid;

-- Loose/consumable items (XT60 connectors, screws, wire) are counted rather
-- than individually serialised — 50 connectors shouldn't become 50 rows with
-- 50 serial numbers nobody writes on anything. A bulk part is ONE row
-- carrying a quantity; how many are free is derived from its outstanding
-- approved requests, not stored, so it can't drift out of sync. Serialised
-- parts keep is_bulk = false and quantity = 1 and behave exactly as before.
alter table parts add column if not exists is_bulk boolean not null default false;
alter table parts add column if not exists quantity integer not null default 1;

-- How many units one request row covers. Serialised parts stay at 1 (there's
-- a row per physical unit, grouped by request_group_id); for a bulk item this
-- is how many of the stack were asked for.
alter table requests add column if not exists quantity integer not null default 1;

-- Read receipts for query threads, like a WhatsApp blue tick: when did each
-- side last actually open this thread. Two columns (not one "last read by
-- anyone") since host and student read independently of each other.
alter table queries add column if not exists host_read_at timestamptz;
alter table queries add column if not exists student_read_at timestamptz;

-- Tracks whether a volunteer row's PRESENCE on this team came from the E2C
-- sheet sync (matched off a real team row) versus someone clicking
-- Volunteer directly in the app. Lets a re-sync safely remove someone the
-- real sheet has swapped out, without ever touching a row that came from
-- an actual in-app click — that boundary is what makes auto-removal safe.
alter table event_volunteers add column if not exists synced_from_sheet boolean not null default false;

-- A staff/teacher account (e.g. the teacher in-charge) signs up through the
-- same form as everyone else, but grade/section/admission_no genuinely
-- don't apply to them — this flag lets signup skip those fields instead of
-- asking for meaningless placeholder values. Separate from HOST_EMAILS
-- (which controls host TOOL access) since this is just "which fields make
-- sense for this person," not a permissions check.
alter table users add column if not exists is_staff boolean not null default false;

-- Private RoboKnights <> Exun channel: one flat shared thread (not
-- per-student like queries), visible only to the specific hand-picked
-- people in shared.py's EXUN_CHANNEL_MEMBERS.
create table if not exists exun_channel_messages (
    message_id bigint generated by default as identity primary key,
    sender_id  uuid not null references users(user_id),
    body       text not null,
    created_at timestamptz not null default now()
);

-- Lets the host permanently dismiss a specific sub-event the E2C scan
-- suggests (e.g. a non-robotics one that keeps coming up) so it stops
-- being suggested on every future scan. Keyed by competition NAME, not
-- competition_id — a brand-new competition doesn't have an id yet at the
-- moment it's rejected, and name-keying means a reject made before import
-- still holds once the competition is later imported.
create table if not exists e2c_rejected_events (
    rejected_id      bigint generated by default as identity primary key,
    competition_name text not null,
    event_name       text not null,
    created_at       timestamptz not null default now(),
    unique (competition_name, event_name)
);

-- Registration-deadline reminder (9am IST the day the deadline arrives):
-- stops the daily job emailing the same competition's reminder twice, same
-- pattern as requests.reminder_2day_sent/reminder_1day_sent.
alter table competitions add column if not exists registration_reminder_sent boolean not null default false;

-- Exun channel read receipts: one row per member, since it's a single
-- flat shared channel (not per-thread like Queries' host_read_at/
-- student_read_at pair) — everyone reads it independently of everyone
-- else. unread_reminder_sent_at stops the daily nudge repeating for the
-- same still-unread message, same "sent" guard shape as every other
-- reminder in this app.
create table if not exists exun_channel_reads (
    user_id                 uuid primary key references users(user_id) on delete cascade,
    last_read_at            timestamptz,
    unread_reminder_sent_at timestamptz
);

-- Daily nudge if a host's reply has sat unread by the student for a
-- while — on top of (not instead of) the existing immediate email, for
-- whoever misses/ignores that first one. Never applies to the host side
-- (host is always staff, and this reminder is students-only by design).
alter table queries add column if not exists student_unread_reminder_sent_at timestamptz;

-- Two more lines the E2C sheet's own competition header carries that
-- the app silently discarded until now (only used to COUNT how many
-- large-font lines to skip, never to capture their actual text): the
-- mode line ("Hybrid"/"Offline"/"Online") and the status line ("TO BE
-- CONQUERED"/"TO BE CONQUERED AT ALL COSTS"/etc). Needed to write a
-- competition back out to Nike's List in the same format it reads it
-- in. Manually-added competitions (no E2C source) just leave these blank.
alter table competitions add column if not exists mode text;
alter table competitions add column if not exists priority_label text;

create table if not exists query_messages (
    message_id bigint generated by default as identity primary key,
    query_id   bigint not null references queries(query_id) on delete cascade,
    sender_id  uuid not null references users(user_id),
    body       text not null,
    created_at timestamptz not null default now(),
    edited_at  timestamptz
);

-- Discord integration, Chunk 1: notify + individually tag eligible
-- members in the club's Discord server when a new competition event is
-- added. Nullable and self-linked (Home page) — a member only shows up
-- tagged once THEY'VE pasted in their own Discord User ID; nobody else
-- can see or set it for them but a host (Members page edit, same as
-- every other profile field there).
alter table users add column if not exists discord_user_id text;

-- Every message send_discord_message() actually posts gets logged here —
-- both the automatic new-event notifications and anything sent through
-- the custom-message tool — purely so a host can find and delete an
-- OLDER message later, not just the one they just sent. Deleting a
-- message (delete_discord_message) removes its row here too, so this
-- table only ever reflects what's currently still live in Discord.
create table if not exists discord_messages (
    id         bigint generated by default as identity primary key,
    message_id text not null,
    content    text not null,
    sent_at    timestamptz not null default now()
);

-- Discord integration, Chunk 2: a second channel (the private Exun<>RK
-- channel, its own separate webhook) alongside the original competitions
-- channel. "channel" says which webhook a logged message actually went
-- to, so a later edit/delete knows which one to call — defaults to
-- 'competitions' for every row logged before this column existed.
alter table discord_messages add column if not exists channel text not null default 'competitions';

-- Tracks whether the "all event names finalized" notification (posted to
-- the exun_rk channel once every event under a competition has its full
-- SELECTED roster) has already fired for this competition, so it isn't
-- re-sent on every page load once complete — reset back to false the
-- moment it's no longer complete, so a later re-completion notifies again.
alter table competitions add column if not exists roster_complete_notified boolean not null default false;

-- Feedback / "report an issue" (2026-08-11): a low-friction way for anyone
-- to flag something they hit while actually using the app, via a floating
-- button on every page (see app.py), the moment they notice it rather than
-- whenever they next remember to mention it. Deliberately no category
-- column — someone hitting something odd often can't tell whether it's a
-- "real" bug worth reporting, so the button doesn't ask them to guess.
-- Visible to everyone (not private like queries) so nobody duplicates a
-- report that's already in; only a host can change status or leave a note.
create table if not exists feedback (
    feedback_id bigint generated by default as identity primary key,
    user_id     uuid not null references users(user_id) on delete cascade,
    body        text not null,
    status      text not null default 'open',
    host_notes  text,
    created_at  timestamptz not null default now(),
    resolved_at timestamptz
);
